apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-data-pv
spec:
  storageClassName: {{ .Values.storage.className }}
  capacity:
    storage: {{ .Values.storage.size }}
  accessModes:
    - ReadWriteOnce