apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd-image-updater.argoproj.io/image-list: "{{.Chart.Name}}={{.Values.image.repository}}:{{.Values.image.tag}}"
    argocd-image-updater.argoproj.io/{{.Chart.Name}}.update-strategy: "digest"
