apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name}}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
  selector:
    app: {{ .Chart.Name}}
  type: {{ .Values.service.type }}