image:
  repository: rg.fr-par.scw.cloud/binge-mate/frontend
  tag: dev
  pullPolicy: Always

resources:
  limits:
    cpu: 15m
    memory: 30Mi
  requests:
    cpu: 5m
    memory: 10Mi

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  host: dev-ci.bingemate.fr
  path: /
  pathType: Prefix
  ingressClassName: traefik