apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - image: {{.Values.image.repository}}:{{.Values.image.tag}}
          name: {{ .Chart.Name }}
          imagePullPolicy: {{.Values.image.pullPolicy}}
          env:
            - name: VIDEO_ROOT
              value: /mnt/media
          volumeMounts:
            - mountPath: /mnt/media
              name: media-target-volume
          ports:
            - containerPort: 8080
              name: 8080tcp
              protocol: TCP
          resources:
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
      volumes:
        - name: media-target-volume
          persistentVolumeClaim:
            claimName: {{ .Values.storage.mediaTargetPVC }}
