apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - image: {{.Values.image.repository}}:{{.Values.image.tag}}
          name: {{ .Chart.Name }}
          imagePullPolicy: {{.Values.image.pullPolicy}}
          env:
            - name: PORT
              value: "8080"
            - name: LOG_FILE
              value: "/var/logs/app/golang-app.log"
            - name: KEYCLOAK_URL
              value: {{ .Values.keycloak.url }}
            - name: REALM
              value: {{ .Values.keycloak.realm }}
            - name: CLIENT_ID
              value: {{ .Values.keycloak.clientId }}
            - name: CLIENT_SECRET
              value: {{ .Values.keycloak.clientSecret }}

          volumeMounts:
            - mountPath: /var/logs/app
              name: log-volume
          ports:
            - containerPort: 8080
              name: 8080tcp
              protocol: TCP
          resources:
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
      volumes:
        - name: log-volume
          persistentVolumeClaim:
            claimName: keycloak-service-logs