apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: keycloak-service-logs
spec:
  storageClassName: {{.Values.storage.className}}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{.Values.storage.logs}}