apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - image: {{.Values.image.repository}}:{{.Values.image.tag}}
          name: {{ .Chart.Name }}
          imagePullPolicy: {{.Values.image.pullPolicy}}
          env:
            - name: OPENAPI_PATH
              value: {{ .Values.openapiPath }}
            - name: DB_KIND
              value: {{ .Values.db.kind }}
            - name: DB_HOST
              value: {{ .Values.db.host }}
            - name: DB_PORT
              value: "{{ .Values.db.port }}"
            - name: DB_USERNAME
              value: {{ .Values.db.user }}
            - name: DB_PASSWORD
              value: {{ .Values.db.password }}
            - name: DB_NAME
              value: {{ .Values.db.name }}
            - name: DB_GENERATION
              value: {{ .Values.db.ddl }}
          ports:
            - containerPort: 8080
              name: 8080tcp
              protocol: TCP
          resources:
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
