image:
  repository: kong/httpbin
  tag: latest
  pullPolicy: Always

resources:
  limits:
    cpu: 3m
    memory: 60Mi
  requests:
    cpu: 1m
    memory: 40Mi

service:
  type: ClusterIP
  port: 80