image:
  bitnamiTag: 14

resources:
  limits:
    cpu: 50m
    memory: 150Mi
  requests:
    cpu: 10m
    memory: 50Mi

db:
  name: postgres
  user: postgres
  password: postgres

service:
  type: NodePort
  port: 5432
  nodePort: 30001

storage:
  className: "nfs-client"
  size: 5Gi