image:
  repository: rg.fr-par.scw.cloud/binge-mate/keycloak-service
  tag: dev
  pullPolicy: Always

resources:
  limits:
    cpu: 50m
    memory: 30Mi
  requests:
    cpu: 10m
    memory: 10Mi

service:
  type: ClusterIP
  port: 8080

storage:
  className: "nfs-client"
  logs: 1Gi

keycloak:
  url: "http://localhost:8080"
  realm: "realm"
  clientId: "client-id"
  clientSecret: "secret"